# Generated by Django 3.2.23 on 2023-12-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_imageteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageTeacher',
        ),
    ]
