# Generated by Django 4.2.6 on 2023-11-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenroll',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='courseenroll',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_name', to='accounts.teacher'),
        ),
    ]
